opsfile

diff --git a/ollama/opsfile.yml b/ollama/opsfile.yml
--- a/ollama/opsfile.yml
+++ b/ollama/opsfile.yml
@@ -12,63 +12,72 @@ tasks:
   prereq:
     silent: true
     cmds:
-    - command -v docker >/dev/null 2>&1 || die "docker is required."
+    - docker -v >/dev/null 2>&1 || die "docker is required."
+    - ops util apihost | rg 'http://miniops.me' || die "Nuvolaris miniops required"
 
-  run:
+  check-gpu:
+    silent: true
+    cmds:
+    - |
+      echo "Checking GPU"
+      if nvidia-smi -L 2>/dev/null | rg ^GPU
+      then  echo GPU Found
+            echo "--gpu all -e OLLAMA_USE_CUDA=1" >_docker
+      else  echo GPU not found
+            echo "" >_docker
+      fi
+
+  start:
     silent: true
     desc: run/reconfigure ollama container from current config
     cmds:
-    - task: prereq
+    - test -e _docker || die "check-gpu before"
     - |
-      IMAGE="${BESTIA_IMAGES_OLLAMA:-docker.io/ollama/ollama:0.15.4}"
-
-      USE_GPU=""
-      if docker info 2>/dev/null | rg -qi nvidia
-      then
-        USE_GPU="--gpus all"
-      else
-        echo "no gpu found - very slow llm only"
-      fi
-
       docker rm -f ollama >/dev/null 2>&1 || true
-
       docker run -d \
-        --name ollama \
-        --restart unless-stopped \
-        $USE_GPU \
-        -p 11434:11434 \
-        -v $HOME/.ollama:/root/.ollama \
-        -e OLLAMA_KEEP_ALIVE=20m \
-        -e OLLAMA_USE_CUDA=1 \
-        $IMAGE >/dev/null
-
+      --name ollama \
+      --restart unless-stopped \
+      -p 11434:11434 \
+      -v $HOME/.ollama:/root/.ollama \
+      -e OLLAMA_KEEP_ALIVE=20m \
+      $(cat _docker) $TRUSTABLE_IMAGES_OLLAMA >/dev/null
+    - |
       docker network create nuvolaris-ollama >/dev/null 2>&1 || true
       docker network connect nuvolaris-ollama ollama >/dev/null 2>&1 || true
       docker network connect nuvolaris-ollama nuvolaris-control-plane >/dev/null 2>&1 || true
 
-  setup:
-    desc: setup ollama
+  preload:
+    silent: true
+    desc: preload models
+    cmds:
+    - |
+      for i in $(cat ../model.lst)
+      do docker exec -ti ollama ollama pull "$i"
+      done
+
+  deploy:
+    desc: deploy ollama
     silent: true
     cmds:
-    - task: run
+    - task: prereq
+    - task: check-gpu
+    - task: start
     - task: preload
 
-  uninstall:
-    desc: uninstall ollama
+  undeploy:
+    desc: undeploy ollama
     silent: true
     ignore_errors: true
     cmds:
     - |
       if docker ps -a | rg ollama
       then
-          docker rm -f ollama-auth-proxy >/dev/null 2>&1 || true
           docker network disconnect nuvolaris-ollama ollama >/dev/null 2>&1 || true
           docker rm -f ollama
           docker network disconnect nuvolaris-ollama nuvolaris-control-plane >/dev/null 2>&1 || true
           docker network rm nuvolaris-ollama >/dev/null 2>&1 || true
           echo Ollama stopped
       else
-          docker rm -f ollama-auth-proxy >/dev/null 2>&1 || true
           echo Ollama is not running
       fi
 
